runtime: nodejs20
service: default
instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

# Static file serving for client-only SPA
handlers:
  - url: /
    static_files: dist/client/index.html
    upload: dist/client/index.html
  - url: /(.*)
    static_files: dist/client/\1
    upload: dist/client/.*

