runtime: nodejs20
service: default
instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  DATA_PROVIDER: firestore
  FIRESTORE_PROJECT_ID: ""
  FIRESTORE_CLIENT_EMAIL: ""
  FIRESTORE_DATABASE_ID: "(default)"

